version: "3.9"

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        env_file: .env
        depends_on:
            - db
            - migrations
    
    migrations:
        container_name: api-migrations
        build:
            context: .
            dockerfile: ./migrations/Dockerfile
        env_file: .env
        depends_on:
            - db

    db:
        container_name: api-db
        restart: unless-stopped
        ports:
            - 5432:5432
        image: postgres:13.3
        environment:
            POSTGRES_DB: priority_queue_web_api_dev
            POSTGRES_PASSWORD: postgres
            